name: test
concurrency:
  group: test-${{ github.github.base_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm -w install
      
      - name: Build
        run: pnpm -w build

      - name: Install dependencies in example app
        run: pnpm --filter @7nohe/react-app install
      
      - name: Run codegen
        run: pnpm --filter @7nohe/react-app generate:api

      - name: Archive generated query file
        uses: actions/upload-artifact@v3
        with:
          name: generated-query-file-${{ matrix.os }}
          path: examples/react-app/openapi/queries/index.ts

      - name: Run tsc
        run: pnpm --filter @7nohe/react-app test:generated
